# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160312_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
