# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_material_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialMarkData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ru', models.CharField(max_length=100)),
                ('en', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='materialmark',
            name='data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.MaterialMarkData'),
        ),
    ]
