# -*- coding: utf-8 -*-
MAXLEN_MATERIAL_MARK_NAME = 30
MAXLEN_MATERIAL_MARK_BLOCK_NAME = 30
MAXLEN_AUTHOR_NAME = 30

MAXLEN_MATERIAL_MARK_DATA = 100

DEFAULT_LANG = 'en'
SUPPORTED_LANGS = ['ru', 'en']
